### ISSUE TITLE
"Error mounting /dev/cdrom: mount: mount point ,nosuid doesnot exist"

### ISSUE THREAD

**Issue by xee5ch** [RedHatOfficial/ansible-role-rhel7-stig#2]
I am not sure why it seems the vars are not being passed correctly, but when attempting to use the following Ansible playbook:

```
---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-rhel
    - geerlingguy.jenkins
    - Ansible-Security-Compliance.rhel7-role-stig-rhel7-disa
```

With the following requirements file.

```
- src: geerlingguy.nfs
- src: geerlingguy.packer-rhel
- src: geerlingguy.jenkins
- src: Ansible-Security-Compliance.rhel7-role-stig-rhel7-disa
```
To build [a commonly used Packer template for CentOS 7](https://github.com/geerlingguy/packer-centos-7), I always receive the same error.

```
   virtualbox-iso: TASK [Ansible-Security-Compliance.rhel7-role-stig-rhel7-disa : get back device fstype] ***
    virtualbox-iso: changed: [127.0.0.1]
    virtualbox-iso:
    virtualbox-iso: TASK [Ansible-Security-Compliance.rhel7-role-stig-rhel7-disa : Ensure permission nosuid are set on var_removable_partition] ***
    virtualbox-iso: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error mounting /dev/cdrom: mount: mount point ,nosuid doesnot exist\n"}
    virtualbox-iso:     to retry, use: --limit @/tmp/packer-provisioner-ansible-local/5b9db65b-4232-93ae-01d3-9ece17dcf5b4/main.retry
    virtualbox-iso:
    virtualbox-iso: PLAY RECAP *********************************************************************
    virtualbox-iso: 127.0.0.1                  : ok=89   changed=53   unreachable=0    failed=1
    virtualbox-iso:
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Ansible: Non-zero exit status: 2
```

I have tried `/dev/sr0` and playing with the `var_removable_partition` variable with no success.  Is this normal behavior or an obvious Ansible playbook error I misunderstand?
